### PR TITLE
Syntax correcting, bug fixing, style changing

### PR DESCRIPTION
**Pull request by dufeiyu**
1. correct some syntax errors and fill some missing variables
2. make remove_rundir task run after all scatter jobs done
3. order_by of several tasks is an array of string, not string. It can take gather_files.done of all scatter jobs
4. Remove tab in command block of dragen_align task. Mixing of tab and whitespace in command block will return error.
5. fix style/indentation to be more readable
6. fix input json file

Now both wdl and json pass womtool-57 validator.

### CODE REVIEW

**Review by dhspence — CHANGES_REQUESTED** [review]
looks good. two comments:

-make the default readfamilysize=1.
-gather_files.done is going to be an array because its inside the scatter command. thats why I used 'select_first'. Think we need a way to indicate that batch_qc shouldnt start until ALL the scatter commands are through.

**Comment by dufeiyu** [comment]
Yes, in "order_by=gather_files.done" gather_files.done is an array and that is why I set order_by type as "Array[String]" inside task input block. With "order_by=gather_files.done", all three tasks: batch_qc, remove_rundir and move_demux_fastq will wait for all scatter sub_jobs' gather_files done then proceed.  
The same way is used in MyeloseqHD.wdl. See below:
https://github.com/genome/cle-myeloseqhd/blob/4e63d443742d77a64967185dffd10d25f7d78cdd/MyeloseqHD.wdl#L156

**Comment by dhspence** [comment]
Looks good!

**Review by dhspence — APPROVED** [review]
done

**Pull request merged**
